version: '3.8'

services:
  flink-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-job
    networks:
      - flink-net
    environment:
      - SOURCE_DB_HOST=your_source_db_host
      - TARGET_DB_HOST=your_target_db_host
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - SOURCE_DB_NAME=your_source_db_name
      - TARGET_DB_NAME=your_target_db_name
    volumes:
      - ./src:/app/src  # Monte o diretório de código fonte
    command: ["python", "src/main_job.py"]

networks:
  flink-net:
    driver: bridge
